aea/config/routes.rb
Rails.application.routes.draw do

  namespace :api, :defaults => {:format => 'json'} do
    devise_for :users
    post "seat_managements/get_occupied_seats_json" => "seat_managements#get_occupied_seats_json"
    post "seat_managements/update_occupied_seat_json" => "seat_managements#update_occupied_seat_json"
  end

  get "area_names/get_all_area_names_json" => "area_names#get_all_area_names_json"
  post "area_names/update_from_api" => "area_names#update_from_api"
  get "occupied_seats/get_all_occupied_seats_json" => "occupied_seats#get_all_occupied_seats_json"
  get "occupied_seats/update_occupied_seats_api" => "occupied_seats#update_occupied_seats_api"
  get "occupied_seats/clear_all_seat_api" => "occupied_seats#clear_all_seat_api"
  get "occupied_seats/send_image" => "occupied_seats#send_image"
  get "occupied_seats/login_with_api" => "occupied_seats#login_with_api"
  get "occupied_seats/verify_with_api" => "occupied_seats#verify_with_api"
  post "occupied_seats/update_seat" => "occupied_seats#update_seat", :as => "update_seat"
  
  resources :area_names
  resources :occupied_seats
  post "seat_managements/get_occupied_seats_json" => "seat_managements#get_occupied_seats_json"
  resources :seat_managements
  delete "seat_managements/delete_all" => "seat_managements#delete_all", :as => "delete_all_sests"
  devise_for :users, :controllers => { registrations: 'registrations' }
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
      get 'register_event'
      patch 'save_register_event'
      get 'update_price'
    end
  end

  get "users" => "users/dashboard#index", as: 'users'
  get "admin" => "admin/dashboard#index", as: 'admin'

  root 'seat_managements#index'

end

aea/app/models/occupied_seat.rb
class OccupiedSeat < ActiveRecord::Base
  belongs_to :area_name
end

aea/app/controllers/occupied_seats_controller.rb
class OccupiedSeatsController < ApplicationController
  before_filter :find_occupied_seat, :only => [:edit, :update, :update_from_api, :destroy, :delete]

  def index
    @area_names = AreaName.all
    @occupied_seats = OccupiedSeat.all.page(params[:page]).per(10)
    @no = paging(10)
  end

  def new
    @occupied_seat = OccupiedSeat.new
  end

  def create
    @occupied_seat = OccupiedSeat.new(area_name_params)
    if @occupied_seat.save
      save_price
      flash[:notice] = 'OccupiedSeat was successfully create.'
      redirect_to occupied_seats_path
    else
      flash[:error] = "OccupiedSeat failed to create"
      render :action => :new
    end
  end

  def update_seat
    puts "===="
    puts params.inspect
    puts "====----"
    @area_name = AreaName.find_by_permalink(params[:id])
    puts @area_name.inspect
    if @area_name.nil?
    redirect_to seat_management_path(current_user.area_names.first.permalink)
      redirect_to seat_management_path(params[:id])
    end

    @seat = OccupiedSeat.where("seat_row = #{params[:seat_row]} AND seat_number = #{params[:seat_number]} AND
                                area_name_id = #{@area_name.id}").first
    if params[:type].downcase == "create"
      puts "-------create"
      if @seat.nil?
        @seat = OccupiedSeat.create(:seat_row => params[:seat_row], :seat_number => params[:seat_number],
                                    :area_name_id => @area_name.id, :status => "1")
      else
        @seat.update_attribute(:status, "1")
      end
    elsif params[:type].downcase == "delete"
      unless @seat.nil?
        @seat.update_attribute(:status, "0")
      end
    end
puts "last"
puts @seat.inspect
    respond_to do |format|
      format.js
      format.html
    end
  end

  def book_seats
    puts "===="
    puts params.inspect
    puts "====----"
    @area_name = AreaName.find_by_permalink(params[:id])
    if @area_name.nil?
    redirect_to seat_management_path(current_user.area_names.first.permalink)
      redirect_to seat_management_path(params[:id])
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
  end

  def update
    if @occupied_seat.update_attributes(occupied_seat_params)
      flash[:notice] = 'OccupiedSeat was successfully updated.'
      redirect_to occupied_seats_path
    else
      flash[:error] = "OccupiedSeat failed to update"
      render :action => :edit
    end
  end

  def destroy
    flash[:notice] =  @occupied_seat.destroy ? 'OccupiedSeat was successfully deleted.' :
                                           'OccupiedSeat was falied to delete.'
    redirect_to occupied_seats_path
  end

  def get_all_occupied_seats_json
    puts params.inspect
    area_name = AreaName.find_by_permalink(params[:area_name])
    raise "Cannot find Area Name" if area_name.nil?
    @occupied_seats = area_name.occupied_seats
    resp = {return_code: 1, error_msg: "", occupied_seats: @occupied_seats}
  rescue Exception => e
    resp = {return_code: 0, error_msg: e.message}

  ensure
    render json: MultiJson.dump(resp)
  end

#  :seat_coordinate => [
#    {:id => 1, :status => 1, :name => "a1"},
#    {:id => 2, :status => 1, :name => "a1"},
#    {:id => 1, :status => 1, :name => "a1"},
#    {:id => 1, :status => 1, :name => "a1"},
#    {:id => 1, :status => 1, :name => "a1"},
#    }]
#
#  :seat_coordinate => "b1 b2 b3 a5 a6"


  #{:area_name => "front", :column_name => "I", :seat_coordinate => ['0-0-1', '0-2-1','0-3-0', '0-4-1']}
  def update_occupied_seats_api
    #params = {:area_name => "front", :column_name => "I", :seat_coordinate => ['0-1-0', '0-2-0','0-3-1', '0-4-0']}
    area_name = AreaName.find_by_permalink(params[:area_name])
    raise "Cannot find Area Name" if area_name.nil?
    raise "Seat Coordinate is blank" if params[:seat_coordinate].blank?
    ActiveRecord::Base.transaction do
      params[:seat_coordinate].each do |location|
        location = location.split("-")
        coordinate = "#{location[0]}-#{location[1]}"
        state = location[2]
        occupied_seat = OccupiedSeat.where("column_name = '#{params[:column_name]}' AND
                                            seat_coordinate = '#{coordinate}' AND
                                            area_name_id = #{area_name.id} ").first
        if occupied_seat.blank?
          occupied_seat = OccupiedSeat.new
          occupied_seat.column_name = params[:column_name]
          occupied_seat.seat_coordinate = coordinate
          occupied_seat.status = state
          occupied_seat.area_name_id = area_name.id
        else
          occupied_seat.status = state
        end

        raise "Cannot Save Seat with location '#{location}' \n #{occupied_seat.errors}" unless occupied_seat.save
      end
    end

    @occupied_seats = area_name.occupied_seats
    resp = {return_code: 1, error_msg: "", occupied_seats: @occupied_seats}
  rescue Exception => e
    @occupied_seats = area_name.occupied_seats
    resp = {return_code: 0, error_msg: e.message, occupied_seats: @occupied_seats}
  ensure
    render json: MultiJson.dump(resp)
  end

  def clear_all_seat_api
    area_name = AreaName.find_by_permalink(params[:area_name])
    raise "Cannot find Area Name" if area_name.nil?
    occupied_seats = OccupiedSeat.where("area_name_id = #{area_name.id}")
    notice = occupied_seats.delete_all ? "All Seat successfully clear" : "Failed clear all seat"
    resp = {return_code: 1, error_msg: notice}
  rescue Exception => e
    resp = {return_code: 0, error_msg: e.message}
  ensure
    render json: MultiJson.dump(resp)
  end

  def send_image
    resp = {user_email: 'martin.me15@yahoo.com', user_token: 'oGsLmVBCQ3XfpzzczgBL', doc_ids: [11,12,13,14]}
    folder_hash = {}
    base64_images = []
    address = "/Users/martin/Downloads/aaa.jpeg"
    base64_images << "data:image/png;base64,#{Base64.encode64(File.open(address, "rb").read)}"
    base64_images << "data:image/png;base64,#{Base64.encode64(File.open(address, "rb").read)}"
    base64_images = ''#"data:image/png;base64,#{Base64.encode64(File.open(address, "rb").read)}"
    folder_hash = folder_hash.merge(id: 1)
    folder_hash = folder_hash.merge("file_name" => base64_images)
    resp = resp.merge(folder_hash)
    response = HTTParty.delete("http://localhost:4001/api/users/sign_out", {body: resp})
    data = JSON.parse(response.body)
    zip_data = File.read(data["url"])
    send_data(zip_data, :type => 'application/zip', :filename => "archive_#{Time.now.to_s(:db)}.zip")
    #render :nothing => true, :status => 200, :content_type => 'text/html'
  rescue Exception => e
    resp = {return_code: 0, error_msg: e.message}
    render :nothing => true, :status => 200, :content_type => 'text/html'
#  ensure
#    render json: MultiJson.dump(resp)
  end

  def login_with_api
    params = {user_login: {email: 'martin.me15@yahoo.com', password: '111111', user_token: '_bKyAgs_twyxU7JSKh7k'},user_email: 'martin.me15@yahoo.com', user_token: '_bKyAgs_twyxU7JSKh7k'}
    response = HTTParty.delete("http://localhost:4001/api/users/sign_out", {body: params})
    puts "----------11"
    puts response.body.inspect
    puts "----------22"
    render :nothing => true, :status => 200, :content_type => 'text/html'
  end

  def verify_with_api
    params = {user_email: 'martin.me15@yahoo.com', user_token: 'XyLwLm9cQWPwWkmB9y6p'}
    response = HTTParty.get("http://localhost:4001/api/api_folders", {body: params})
    puts "----------11"
    puts response.body.inspect
    puts "----------22"
    @result = JSON.parse(response.body)["folders"]
    #render :nothing => true, :status => 200, :content_type => 'text/html'
  end

  private

    def occupied_seat_params
      params.require(:occupied_seat).permit(:area_name_id, :seat_number, :seat_row, :status, :updated_by)
    end

    def find_occupied_seat
      @occupied_seat = OccupiedSeat.find_by_id(params[:id])
      if @occupied_seat.nil?
        flash[:notice] = "Cannot find the RoomType with id '#{params[:id]}'"
        redirect_to occupied_seats_path
     end
    end

end

aea/app/views/occupied_seats/index.html.erb
<div class="col-md-12 content">
  <h2>Seats</h2>
  <div class="col-md-12">
    <p><%#= raw msg_flash(flash) %></p>
    <p>
      <%= link_to "Add new area_name", new_area_name_path %>
    </p>
    <div class="col-xs-12 product-detail-specification">
      <div class="panel with-nav-tabs panel-default">
        <div class="panel-heading">
          <ul class="nav nav-tabs">
            <% @area_names.each_with_index do |area_name, x| %>
              <% active = "class='active'" if x == 0 %>
              <li <%= active %>>
                <a href="#<%= area_name.name %>" data-toggle="tab"><%= area_name.name %></a>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="panel-body">
          <div class="tab-content">
            <div class="tab-pane fade in active" id="specification">
              <% @product_specifications.each do |type, files| %>
              <div class="col-xs-12 no-padding-lr" id="<%= 'spec-image' if type.downcase == 'image' %>">
                  <% files.each do |file| %>
                    <% if type.downcase == 'image' %>
                      <div class="col-xs-6 col-sm-3">
                        <div class="product-specification-box">
                          <%= link_to (image_tag file.filename.url(:medium), :class => "img-loading img-responsive"),
                                      file.filename.url, :title => file.filename.file.filename %>
                        </div>
                      </div>
                    <% else %>
                      <div class="col-xs-12">
                        <div class="col-xs-12 product-file">
                          <p>
                            <%= link_to file.filename.file.filename, file.filename.url,
                                        :target => "_blank" %>
                          </p>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            </div>
            <div class="tab-pane fade" id="certification">
              <% @certificates.each do |certificate| %>
                <%= link_to raw("
                  <div class='col-xs-6 col-md-4 col-lg-3 no-padding-lr certificate'>
                    <div class='certificate-image'>
                      #{image_tag certificate.image.url(:medium), :class => "img-loading img-responsive"}
                    </div>
                    <div class='certificate-name'>
                      #{certificate.name}
                    </div>
                  </div>
                "), certificate.file.url, :target => "_blank" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>














    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Main Column</th>
          <th>Total Row</th>
          <th>Seats/row</th>
          <th>Status</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% @area_names.each_with_index do |area_name, x| %>
          <tr>
            <th scope="row"><%= @no+x+1 %></th>
            <td><%= area_name.name %></td>
            <td><%= area_name.main_column %></td>
            <td><%= area_name.total_row %></td>
            <td><%= area_name.seats_per_row %></td>
            <td><%= area_name.status ? "Active" : "Inactive" %></td>
            <td>
              <%= link_to "Edit", edit_area_name_path(area_name), :class => "btn btn-success" %>
              <%= link_to "Delete", area_name_path(area_name.id ), :method => :delete,
                                    data: {:confirm => "Are you sure?"}, :class => "btn btn-warning" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="admin-row">
      <%= paginate @area_names, :link_separator => " | ",
                                 :previous_label => "&laquo; previous",
                                 :next_label => "next &raquo;" %>

    </div>
  </div>
</div>

aea/app/views/occupied_seats/update_seat.js.erb
<% if @seat.nil? %>
  alert("update failed");
<% end %>
$("#img"+<%= params[:seat_row] %>+"-"+<%= params[:seat_number] %>).hide();
$("span#"+<%= params[:seat_row] %>+"-"+<%= params[:seat_number] %>).show();

aea/app/views/occupied_seats/verify_with_api.html.erb
<% @result.each do |data|  %>
  folder name <%= data["folder_name"] %><br/>
  folder id <%= data["folder_id"] %><br/>
  <%= data["documents"].each do |doc| %>
    name <%= doc['doc_name']  %>--
    id <%= doc['doc_id']  %>--
    gambar <%= doc['doc_encoded']  %>
  <% end %><br/>
<% end %>