aea/config/routes.rb
Rails.application.routes.draw do

  namespace :api, :defaults => {:format => 'json'} do
    devise_for :users
    post "seat_managements/get_occupied_seats_json" => "seat_managements#get_occupied_seats_json"
    post "seat_managements/update_occupied_seat_json" => "seat_managements#update_occupied_seat_json"
  end

  get "area_names/get_all_area_names_json" => "area_names#get_all_area_names_json"
  post "area_names/update_from_api" => "area_names#update_from_api"
  get "occupied_seats/get_all_occupied_seats_json" => "occupied_seats#get_all_occupied_seats_json"
  get "occupied_seats/update_occupied_seats_api" => "occupied_seats#update_occupied_seats_api"
  get "occupied_seats/clear_all_seat_api" => "occupied_seats#clear_all_seat_api"
  get "occupied_seats/send_image" => "occupied_seats#send_image"
  get "occupied_seats/login_with_api" => "occupied_seats#login_with_api"
  get "occupied_seats/verify_with_api" => "occupied_seats#verify_with_api"
  post "occupied_seats/update_seat" => "occupied_seats#update_seat", :as => "update_seat"
  
  resources :area_names
  resources :occupied_seats
  post "seat_managements/get_occupied_seats_json" => "seat_managements#get_occupied_seats_json"
  resources :seat_managements
  delete "seat_managements/delete_all" => "seat_managements#delete_all", :as => "delete_all_sests"
  devise_for :users, :controllers => { registrations: 'registrations' }
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
      get 'register_event'
      patch 'save_register_event'
      get 'update_price'
    end
  end

  get "users" => "users/dashboard#index", as: 'users'
  get "admin" => "admin/dashboard#index", as: 'admin'

  root 'seat_managements#index'

end

aea/app/views/shared/_user_side_menu.html.erb
<div class="col-md-3 padding_t_20">
  <div class="col-md-12 padding_t_b_5">
    <%= link_to "Edit Profile", edit_user_registration_path,
                class: active_side_menu("registrations") %>
  </div>
  <div class="col-md-12 padding_t_b_5">
    <%= link_to "Registration", register_event_user_path,
                class: active_side_menu(["register_event", "save_register_event"]) %>
  </div>
  <div class="col-md-12 padding_t_b_5 active">
    <%= link_to "Change Password", edit_user_path,
                class: active_side_menu(["edit", "update_password"]) %>
  </div>
  <% if current_user.is_indonesian? %>
    <div class="col-md-12 padding_t_b_5">
      <%= link_to "Payment Confirmation", new_users_payment_confirmation_path,
                   class: active_side_menu('payment_confirmations') %>
    </div>
  <% end %>
  <div class="col-md-12 padding_t_b_5">
    <%= link_to "Travel Informations", users_edit_pick_up_schedule_path,
                class: active_side_menu('pick_up_schedule') %>
  </div>
  <% if current_user.is_team_lead? %>
    <div class="col-md-12 padding_t_b_5">
      <%= link_to "Register National Alliance Delegates", users_registrants_path,
                  class: active_side_menu("registrants") %>
    </div>
  <% end %>
  <% unless current_user.payment_method_is_transfer_bank? %>
    <div class="col-md-12 padding_t_b_5">
      <%= link_to "Upload Ticket", edit_users_ticket_path(current_user.ticket || 0),
                  class: active_side_menu('tickets') %>
    </div>
  <% end %>
</div>